### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sdavis00255**
Brandon Davis and Steven Davis. Added a race functionality.

### CODE REVIEW

**Comment by mikeknows** [comment]
Please resolve merge conflict

**Review by mikeknows — CHANGES_REQUESTED** [review]
Main.java, I am unable to see the changes

**Comment by sdavis00255** [comment]
I am trying to find out how to make it show just the updated lines rather than it seeing the whole document being edited. I am not sure why it is doing that.

**Comment by sdavis00255** [comment]
It looks like it took this time.

**Review by sdavis00255 — COMMENTED** [review]
Updated the files

**Comment by mikeknows** [comment]
Merge conflict

**Comment by sdavis00255** [comment]
What is causing this to fail?

**Review by mikeknows — CHANGES_REQUESTED** [review]
Build failed through travisCI. Has to be a compilation error.

**Comment by sdavis00255** [comment]
How about now?

**Pull request merged**
