### PR TITLE
Harold Farmer and Stan Hostetler

### PR DESCRIPTION
**Pull request by haroldfarmer**
Stan added compare wrestler button and text field and the listview for that as well as alert boxes and modified the Model file to bring over wrestler information to the main file. Harold added the listview for the start as well as some alert boxes and changed the model file to bring information to the main. The additions make the GUI more functional and more user friendly. Previous pull request was from wrong branch.

### CODE REVIEW

**Comment by mikeknows** [comment]
Merge conflict

**Comment by haroldfarmer** [comment]
Stan and I fixed the conflicts which was we added something to the same line as another group, and we added a button to the same spot on the grid.

**Comment by mikeknows** [comment]
Another merge conflict after accepting PRs

**Comment by haroldfarmer** [comment]
Fixed the issues

**Pull request merged**
