### PR TITLE
Added a Add button

### PR DESCRIPTION
**Pull request by Turah09**
Allows the user to insert a new wrestler using the GUI

### CODE REVIEW

**Comment by mikeknows** [comment]
Merge conflict

**Comment by Turah09** [comment]
I have changed the file. there was an extra line of add event, also extra crap. It working. My project 2 was affected when someone else pushed extra lines of code. I also fix all the bugs so now it will compile.

**Comment by Turah09** [comment]
Before:
before
After:
after(Intro)

**Comment by Turah09** [comment]
After main page:

image

**Pull request merged**
